### ISSUE TITLE
Crash because of missing menu item

### ISSUE THREAD

**Issue by mikaelsvensson** [devscoutsweden/aktivitetsbanken-android#120]
This error log was sent to us by e-mail:

```
App version: 0.1 (13)
Android release: 5.0.2
Device: Sony D6603 D6603 D6603

13:28:34.689 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

13:28:34.690 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

13:28:34.691 [thread 155521] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

13:28:34.696 [thread 155521] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:34.713 [thread 155521] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

13:28:34.719 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: State (e.g. search result) has been restored.

13:28:34.733 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

13:28:34.755 [thread 155521] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

13:28:34.781 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of onPostExecute

13:28:34.783 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of onPostExecute

13:28:36.304 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

13:28:36.304 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

13:28:36.305 [thread 155523] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

13:28:36.306 [thread 155523] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:36.306 [thread 155523] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

13:28:36.345 [thread 155523] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

13:28:36.349 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

13:28:36.353 [thread 155524] se.devscout.android.view.NonBlockingSearchView: Start of doInBackground as part of se.devscout.android.view.SearchHistoryListView

13:28:36.353 [thread 155524] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:36.353 [thread 155524] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

13:28:36.390 [thread 155524] se.devscout.android.view.NonBlockingSearchView: End of doInBackground as part of se.devscout.android.view.SearchHistoryListView

13:28:36.432 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of onPostExecute

13:28:36.433 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of onPostExecute

13:28:36.476 [thread 1] se.devscout.android.view.NonBlockingSearchView: Search task has completed.

13:28:36.476 [thread 1] se.devscout.android.view.NonBlockingSearchView: 8 items were returned.

13:28:36.477 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

13:28:36.477 [thread 1] se.devscout.android.view.NonBlockingSearchView: Measurements:
|         0 ms Starting stopwatch SearchTask
|         0 ms initExceptionLogging done
|         0 ms Start of onPreExecute
|         0 ms End of onPreExecute
|         1 ms Start of doSearch
|        35 ms End of doSearch
|        87 ms Start of onPostExecute
|         0 ms End of onPostExecute
|       125 ms Total

13:28:37.424 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

13:28:37.425 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

13:28:37.426 [thread 155526] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

13:28:37.426 [thread 155526] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:37.426 [thread 155526] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

13:28:37.447 [thread 155526] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

13:28:37.541 [thread 155530] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

13:28:37.547 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: State (e.g. search result) has been restored.

13:28:37.549 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:37.550 [thread 155530] se.devscout.android.util.InstallationProperties: Installation properties file is /data/data/se.devscout.android/files/installation.properties

13:28:37.552 [thread 155530] se.devscout.android.util.InstallationProperties: Installation properties file is about to be read.

13:28:37.561 [thread 155530] se.devscout.android.util.InstallationProperties: 1 installation properties have been read from file.

13:28:37.561 [thread 155530] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

13:28:37.561 [thread 155530] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/categories

13:28:37.582 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

13:28:37.585 [thread 1] se.devscout.android.util.LogUtil: Thread 'main' (id: 1) crashed due to uncaught java.lang.RuntimeException
java.lang.RuntimeException: Unable to start activity ComponentInfo{se.devscout.android/se.devscout.android.controller.activity.StartActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
at android.app.ActivityThread.access$800(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5321)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
at se.devscout.android.controller.activity.StartActivity.onPrepareOptionsPanel(StartActivity.java:92)
at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:480)
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:580)
at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:921)
at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:262)
at com.android.internal.policy.impl.PhoneWindow.doPendingInvalidatePanelMenu(PhoneWindow.java:895)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2012)
at android.app.Activity.onRestoreInstanceState(Activity.java:1022)
at android.app.Activity.performRestoreInstanceState(Activity.java:977)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
... 10 more
```

**Comment by mikaelsvensson** [comment]
"[Felet uppstod när användaren] skulle återgå till appen"
