### ISSUE TITLE
Crash on profile screen

### ISSUE THREAD

**Issue by mikaelsvensson** [devscoutsweden/aktivitetsbanken-android#121]
Crash report:
```
14:25:23.760 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

14:25:23.760 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

14:25:23.761 [thread 157441] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

14:25:23.761 [thread 157441] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

14:25:23.761 [thread 157441] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

14:25:23.767 [thread 157441] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

14:25:23.783 [thread 157443] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

14:25:23.785 [thread 157443] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, display_name, api_key, email_address FROM user

14:25:23.788 [thread 157443] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

14:25:23.789 [thread 157443] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

14:25:23.789 [thread 157443] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/users/profile

14:25:23.821 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of onPostExecute

14:25:23.822 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of onPostExecute

14:25:23.914 [thread 157443] se.devscout.android.util.http.HttpRequest: Measurements:
|         0 ms Starting stopwatch readUrl http://aktivitetsbanken.devscout.se:80/api/v1/users/profile
|         0 ms Connection has been opened
|         0 ms Data sent
|       124 ms Done
|       124 ms Total

14:25:23.914 [thread 157443] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Server said that user is unauthorized

14:25:23.915 [thread 1] se.devscout.android.util.LogUtil: Thread 'main' (id: 1) crashed due to uncaught java.lang.NullPointerException
java.lang.NullPointerException: Attempt to get length of null array
at android.text.TextUtils.join(TextUtils.java:298)
at se.devscout.android.controller.fragment.AuthUserProfileFragment$4.onPostExecute(AuthUserProfileFragment.java:127)
at se.devscout.android.controller.fragment.AuthUserProfileFragment$4.onPostExecute(AuthUserProfileFragment.java:115)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5321)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by mikaelsvensson** [comment]
Another (identical) report:
```


App version: 0.1 (13)
Android release: 5.0.2
Device: google grouper Nexus 7 nakasi

20:06:00.549 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: State saved

20:06:01.002 [thread 370] se.devscout.android.view.NonBlockingSearchView: End of doInBackground as part of se.devscout.android.view.ActivitiesListView

20:06:01.003 [thread 1] se.devscout.android.view.NonBlockingSearchView: Search task has completed.

20:06:01.003 [thread 1] se.devscout.android.view.NonBlockingSearchView: 6 items were returned.

20:06:01.003 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

20:06:01.004 [thread 1] se.devscout.android.view.NonBlockingSearchView: Measurements:
|         0 ms Starting stopwatch SearchTask
|         0 ms initExceptionLogging done
|         0 ms Start of onPreExecute
|         0 ms End of onPreExecute
|         0 ms Start of doSearch
|         0 ms Acquired ActivityBank
|       212 ms Query server
|       761 ms Added search to history
|         0 ms Created list items
|         0 ms End of doSearch
|         0 ms Start of onPostExecute
|         0 ms End of onPostExecute
|       976 ms Total

20:06:02.507 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

20:06:02.507 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

20:06:02.511 [thread 368] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

20:06:02.512 [thread 368] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.513 [thread 368] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

20:06:02.532 [thread 368] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

20:06:02.552 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: readActivities: missing=150 existing=

20:06:02.553 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Requesting data for these server-only activities: 150

20:06:02.554 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.556 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.556 [thread 372] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=150

20:06:02.622 [thread 372] se.devscout.android.util.http.ByteArrayResponseStreamHandler: Measurements:
|         0 ms Starting stopwatch Reading stream
|         0 ms Received 3077 bytes from server.
|         0 ms Total

20:06:02.622 [thread 372] se.devscout.android.util.http.HttpRequest: Measurements:
|         0 ms Starting stopwatch readUrl http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=150
|         0 ms Connection has been opened
|         0 ms Data sent
|        65 ms Read 1556 bytes from connection.
|         0 ms Done
|        65 ms Total

20:06:02.622 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Server response: [{"id":150,"revision_id":1163,"_id":150,"_ratings_count":null,"_ratings_average":null,"_favourite_count":null,"_my_rating":null,"_updated_at":"2015-06-07T11:38:30.260Z","_created_at":"2015-06-06T13:06:37.112Z","_related":[{"related_activity_id":344},{"related_activity_id":594},{"related_activity_id":737},{"related_activity_id":833},{"related_activity_id":908}],"updated_at":"2015-06-06T13:57:02.979Z","created_at":"2015-06-06T13:57:02.979Z","name":"Citronleken","descr_introduction":"Ett klurigt problem som kan ge scouterna ett överraskande bra resultat. Dessutom bidrar aktiviteten till att träna scouternas sinnen och förmåga att lösa klurigare problem tillsammans.x","descr_main":"Alla scouter förses med en ögonbindel. När ingen längre kan se något så sprider lekledaren ut lika många citroner på golvet som det finns deltagare. Nu gäller det för alla att hitta varsin citron. När deltagaren har hittat sin citron sätter den sig ned och bekantar sig med den (känner dess doft,...

20:06:02.623 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Measurements:
|         0 ms Starting stopwatch getJSONArray from http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=150
|        66 ms Fetched 2990 characters of data
|         0 ms Parsed data
|        67 ms Total

20:06:02.624 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.633 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of onPostExecute

20:06:02.634 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of onPostExecute

20:06:02.699 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.700 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id, user_id, rating, status FROM rating WHERE activity_id = 1 AND user_id = 1

20:06:02.701 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Measurements:
|         0 ms Starting stopwatch findActivity SERVERID-150
|         0 ms Preparing request
|        67 ms Sending query to server and reading response
|         0 ms Parsed JSON
|        77 ms Saving all returned data in local database
|         0 ms The last things
|       145 ms Total

20:06:02.701 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: readActivities: missing=296 existing=

20:06:02.701 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Requesting data for these server-only activities: 296

20:06:02.701 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.702 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.702 [thread 372] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=296

20:06:02.716 [thread 1] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Could not determine local id based on remote id -1

20:06:02.718 [thread 1] se.devscout.android.controller.fragment.ActivityFragment: Activity has already been loaded.

20:06:02.718 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.719 [thread 1] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id FROM favourite_activity WHERE user_id = 1 AND activity_id = 1

20:06:02.734 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.758 [thread 1] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id, user_id, rating, status FROM rating WHERE activity_id = 1 AND user_id = 1

20:06:02.758 [thread 372] se.devscout.android.util.http.ByteArrayResponseStreamHandler: Measurements:
|         0 ms Starting stopwatch Reading stream
|         0 ms Received 4811 bytes from server.
|         0 ms Total

20:06:02.759 [thread 372] se.devscout.android.util.http.HttpRequest: Measurements:
|         0 ms Starting stopwatch readUrl http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=296
|         0 ms Connection has been opened
|         0 ms Data sent
|        55 ms Read 2580 bytes from connection.
|         0 ms Done
|        56 ms Total

20:06:02.764 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Server response: [{"id":296,"revision_id":1310,"_id":296,"_ratings_count":null,"_ratings_average":null,"_favourite_count":null,"_my_rating":null,"_updated_at":"2015-06-07T11:38:42.675Z","_created_at":"2015-06-06T13:07:01.157Z","_related":[{"related_activity_id":247},{"related_activity_id":570},{"related_activity_id":708},{"related_activity_id":940},{"related_activity_id":980}],"updated_at":"2015-06-06T13:57:32.095Z","created_at":"2015-06-06T13:57:32.095Z","name":"Hajk med detektivbyråtema","descr_introduction":"Man kan få till en väldigt spännande helg genom att skapa några detektivgåtor som scouterna skall lösa.\r\n\r\nFör de yngre barnen kanske böckerna om LasseMajas detektivbyrå kan vara inspiration och göra att barnen känner igen sig. För de äldre finns så klart andra böcker eller tv-serier att inspireras av.","descr_main":"De som ordnar hajken (antas här vara ledarna) behöver planera en hel del för att få till olika detektivgåtor som flätas in i varandra. Det är bra om man är mång...

20:06:02.767 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Measurements:
|         0 ms Starting stopwatch getJSONArray from http://aktivitetsbanken.devscout.se:80/api/v1/activities?id=296
|        61 ms Fetched 4657 characters of data
|         0 ms Parsed data
|        62 ms Total

20:06:02.770 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.799 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.825 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:02.959 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.960 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id, user_id, rating, status FROM rating WHERE activity_id = 2 AND user_id = 1

20:06:02.961 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Measurements:
|         0 ms Starting stopwatch findActivity SERVERID-296
|         0 ms Preparing request
|        65 ms Sending query to server and reading response
|         0 ms Parsed JSON
|       193 ms Saving all returned data in local database
|         0 ms The last things
|       258 ms Total

20:06:02.963 [thread 1] se.devscout.android.controller.fragment.ActivityFragment: Activity has already been loaded.

20:06:02.963 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.963 [thread 1] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id FROM favourite_activity WHERE user_id = 1 AND activity_id = 2

20:06:02.967 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:02.970 [thread 1] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT activity_id, user_id, rating, status FROM rating WHERE activity_id = 2 AND user_id = 1

20:06:03.085 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Saving state

20:06:03.085 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: State saved

20:06:03.085 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Saving state

20:06:03.085 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: State saved

20:06:04.520 [thread 1] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:04.542 [thread 1] se.devscout.android.model.repo.sql.SQLiteActivityRepo: Saved 1 in activity history.

20:06:06.895 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:06.915 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:06.915 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    a.owner_id, a.id, a.server_id, a.server_revision_id, a.is_publishable, a.name, a.datetime_published, a.datetime_created, a.descr_material, a.descr_introduction, a.descr_prepare, a.descr_activity, a.descr_safety, a.descr_notes, a.age_min, a.age_max, a.participants_min, a.participants_max, a.time_min, a.time_max, a.featured, a.favourite_count, a.rating_average from    activity a    inner join favourite_activity fa on fa.activity_id = a.id and fa.user_id = 1 order by a.id

20:06:06.917 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adc.activity_id activity_id,   c.* from    category c inner join activity_categories adc on c.id = adc.category_id where    adc.activity_id in (1)

20:06:06.918 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adm.activity_id activity_id,   m.* from    media m inner join activity_media_items adm on m.id = adm.media_id where    adm.activity_id in (1)

20:06:06.919 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adr.activity_id activity_id,   r.* from    reference r inner join activity_references adr on r.id = adr.reference_id where    adr.activity_id in (1)

20:06:06.919 [thread 372] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:06.921 [thread 372] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:06.921 [thread 372] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/favourites

20:06:06.925 [thread 372] se.devscout.android.util.http.StringRequestBodyStreamHandler: Measurements:
|         0 ms Starting stopwatch Writing to stream
|         0 ms Sent 12 bytes to server.
|         0 ms Total

20:06:06.962 [thread 372] se.devscout.android.util.http.HttpRequest: Measurements:
|         0 ms Starting stopwatch readUrl http://aktivitetsbanken.devscout.se:80/api/v1/favourites
|         0 ms Connection has been opened
|         3 ms Data sent
|        36 ms Done
|        41 ms Total

20:06:06.962 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Server said that user is unauthorized

20:06:06.963 [thread 372] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Something went wrong when communicating with the server
se.devscout.android.util.http.UnauthorizedException
at se.devscout.android.util.http.HttpRequest.run(HttpRequest.java:95)
at se.devscout.android.model.repo.remote.RemoteActivityRepoImpl.readUrl(RemoteActivityRepoImpl.java:1278)
at se.devscout.android.model.repo.remote.RemoteActivityRepoImpl.readUrlAsBytes(RemoteActivityRepoImpl.java:1194)
at se.devscout.android.model.repo.remote.RemoteActivityRepoImpl.sendPutFavouritesRequest(RemoteActivityRepoImpl.java:588)
at se.devscout.android.model.repo.remote.RemoteActivityRepoImpl.setFavourite(RemoteActivityRepoImpl.java:565)
at se.devscout.android.util.concurrency.UpdateFavouriteStatusTaskExecutor.run(UpdateFavouriteStatusTaskExecutor.java:22)
at se.devscout.android.util.concurrency.UpdateFavouriteStatusTaskExecutor.run(UpdateFavouriteStatusTaskExecutor.java:13)
at se.devscout.android.util.concurrency.BackgroundTasksHandlerThread$MessageHandler.handleMessage(BackgroundTasksHandlerThread.java:182)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

20:06:12.153 [thread 1] se.devscout.android.util.concurrency.BackgroundTasksHandlerThread: Closing and clearing

20:06:12.653 [thread 357] se.devscout.android.view.NonBlockingSearchView: Start of doInBackground as part of se.devscout.android.view.FavouriteActivitiesListView

20:06:12.653 [thread 357] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Never ask server for user's favourite activities. Assume that local database is up-to-date since last log-in.

20:06:12.653 [thread 357] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    a.owner_id, a.id, a.server_id, a.server_revision_id, a.is_publishable, a.name, a.datetime_published, a.datetime_created, a.descr_material, a.descr_introduction, a.descr_prepare, a.descr_activity, a.descr_safety, a.descr_notes, a.age_min, a.age_max, a.participants_min, a.participants_max, a.time_min, a.time_max, a.featured, a.favourite_count, a.rating_average from    activity a    inner join favourite_activity fa on fa.activity_id = a.id and fa.user_id = 1 order by a.id

20:06:12.655 [thread 357] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adc.activity_id activity_id,   c.* from    category c inner join activity_categories adc on c.id = adc.category_id where    adc.activity_id in ()

20:06:12.657 [thread 357] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adm.activity_id activity_id,   m.* from    media m inner join activity_media_items adm on m.id = adm.media_id where    adm.activity_id in ()

20:06:12.657 [thread 357] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: select    adr.activity_id activity_id,   r.* from    reference r inner join activity_references adr on r.id = adr.reference_id where    adr.activity_id in ()

20:06:12.658 [thread 357] se.devscout.android.view.NonBlockingSearchView: End of doInBackground as part of se.devscout.android.view.FavouriteActivitiesListView

20:06:12.692 [thread 1] se.devscout.android.view.NonBlockingSearchView: Search task has completed.

20:06:12.692 [thread 1] se.devscout.android.view.NonBlockingSearchView: 1 items were returned.

20:06:12.692 [thread 1] se.devscout.android.controller.fragment.ActivitiesListFragment: Progress view has been hidden and list view has been shown.

20:06:12.692 [thread 1] se.devscout.android.view.NonBlockingSearchView: Measurements:
|         0 ms Starting stopwatch SearchTask
|         0 ms initExceptionLogging done
|         0 ms Start of onPreExecute
|         0 ms End of onPreExecute
|         1 ms Start of doSearch
|         0 ms Acquired ActivityBank
|         5 ms Query server
|         0 ms Created list items
|         0 ms End of doSearch
|        33 ms Start of onPostExecute
|         0 ms End of onPostExecute
|        40 ms Total

20:06:18.637 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of loadSearchHistoryItems

20:06:18.637 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of loadSearchHistoryItems

20:06:18.638 [thread 365] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of doInBackground

20:06:18.638 [thread 365] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:18.638 [thread 365] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, user_id, type, data FROM history WHERE user_id = 1 and type = ? ORDER BY id DESC

20:06:18.655 [thread 365] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of doInBackground

20:06:18.685 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: Start of onPostExecute

20:06:18.685 [thread 1] se.devscout.android.controller.activity.drawer.DrawerListAdapter: End of onPostExecute

20:06:18.699 [thread 367] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:18.702 [thread 367] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, display_name, api_key, email_address FROM user

20:06:18.705 [thread 367] se.devscout.android.model.repo.sql.DatabaseHelper: SQLiteQuery: SELECT id, server_id, server_revision_id, valid_from, valid_to, key, value FROM system_messages

20:06:18.707 [thread 367] se.devscout.android.util.auth.CredentialsManager: Getting current_user_id = 1

20:06:18.707 [thread 367] se.devscout.android.util.http.HttpRequest: Sending request to http://aktivitetsbanken.devscout.se:80/api/v1/users/profile

20:06:18.754 [thread 367] se.devscout.android.util.http.HttpRequest: Measurements:
|         0 ms Starting stopwatch readUrl http://aktivitetsbanken.devscout.se:80/api/v1/users/profile
|         0 ms Connection has been opened
|         0 ms Data sent
|        45 ms Done
|        46 ms Total

20:06:18.754 [thread 367] se.devscout.android.model.repo.remote.RemoteActivityRepoImpl: Server said that user is unauthorized

20:06:18.818 [thread 1] se.devscout.android.util.LogUtil: Thread 'main' (id: 1) crashed due to uncaught java.lang.NullPointerException
java.lang.NullPointerException: Attempt to get length of null array
at android.text.TextUtils.join(TextUtils.java:298)
at se.devscout.android.controller.fragment.AuthUserProfileFragment$4.onPostExecute(AuthUserProfileFragment.java:127)
at se.devscout.android.controller.fragment.AuthUserProfileFragment$4.onPostExecute(AuthUserProfileFragment.java:115)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
