### ISSUE TITLE
Crash after changing tab configuration

### ISSUE THREAD

**Issue by mikaelsvensson** [devscoutsweden/aktivitetsbanken-android#124]
Om användaren väljer att ändra vilka flikar som syns på startskärmen (genom att klicka på kugghjulsknappen in titelraden) så kraschar appen när startskärmen laddas om.

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {se.devscout.android/se.devscout.android.controller.activity.StartActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnecting()' on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:3637)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3680)
at android.app.ActivityThread.access$1300(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5321)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnecting()' on a null object reference
at se.devscout.android.util.auth.GoogleAuthenticationStrategy.onActivityResult(GoogleAuthenticationStrategy.java:136)
at se.devscout.android.util.auth.CredentialsManager.onActivityResult(CredentialsManager.java:128)
at se.devscout.android.controller.activity.SingleFragmentActivity.onActivityResult(SingleFragmentActivity.java:307)
at android.app.Activity.dispatchActivityResult(Activity.java:6135)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3633)
... 10 more
```

**Comment by mikaelsvensson** [comment]
Blir det fel även om inte "inloggningskortet" finns på Hem-fliken?

**Comment by TheSwedishScout** [comment]
Det kraschade för mig  när jag ändrar med kugghjulet men inte via hem-sidan
